function generate_gradspectrum_baseline(seqPath, outPath)
%GENERATE_GRADSPECTRUM_BASELINE  Write a gradSpectrum baseline for SeqEyes CI.
%
%   generate_gradspectrum_baseline('v151_gre/seq/writeGradientEcho.seq', ...
%                                  'v151_gre/baseline/gradspectrum.txt')
%
%   Requires the pulseq MATLAB toolbox on the path, at the revision pinned in
%   README.md (2fd6ab6af5a0cd47b6c15d8e5af09c986eb81007). Record the revision
%   you actually used, plus the MATLAB version, in cases.json.
%
%   Columns written: F, Rx, Ry, Rz, R -- frequency in Hz and the per-axis and
%   combined root-mean-square magnitudes exactly as gradSpectrum reports them
%   (Hz/m, unnormalised). SeqEyes compares its computeGradSpectrumParity output
%   against these within 1e-3 relative.

    arguments
        seqPath (1,:) char
        outPath (1,:) char
    end

    seq = mr.Sequence();
    seq.read(seqPath);

    % [] = default gradient raster, 3000 Hz ceiling, false = do not plot.
    [spectrogram, frequencies] = seq.gradSpectrum([], 3000, false);

    % gradSpectrum returns per-axis rows; the combined trace is the
    % root-sum-of-squares across them, matching R = sum(gs.^2).^0.5 upstream.
    if size(spectrogram, 1) == 3
        axes3 = spectrogram;
    else
        axes3 = spectrogram(1:3, :);
    end
    combined = sqrt(sum(axes3 .^ 2, 1));

    outDir = fileparts(outPath);
    if ~isempty(outDir) && ~isfolder(outDir)
        mkdir(outDir);
    end

    fid = fopen(outPath, 'w');
    if fid < 0
        error('Could not open %s for writing.', outPath);
    end
    cleanup = onCleanup(@() fclose(fid));

    fprintf(fid, '# generated by generate_gradspectrum_baseline.m\n');
    fprintf(fid, '# sequence: %s\n', seqPath);
    fprintf(fid, '# matlab: %s\n', version());
    fprintf(fid, '# F  Rx  Ry  Rz  R\n');
    for k = 1:numel(frequencies)
        fprintf(fid, '%.10e %.10e %.10e %.10e %.10e\n', ...
            frequencies(k), axes3(1, k), axes3(2, k), axes3(3, k), combined(k));
    end

    fprintf('Wrote %d bins to %s\n', numel(frequencies), outPath);
end
